<a href="https://colab.research.google.com/github/oktsadwikar/DPDM2023/blob/main/Frequent_Patterns_(Association_Rules).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path = '/content/drive/MyDrive/DPDM23_DATA'

In [4]:
data = pd.read_csv(os.path.join(path,'reduced_marketbasket.csv'),encoding='latin-1')

In [5]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France

In [6]:
data.groupby('InvoiceNo').max()
# group the row by column Invoice number, and select the max value from each different column to be shown in the table

,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
InvoiceNo,,,,,,,
536365,85123A,WHITE METAL LANTERN,8,12/01/2010 08:26,7.65,17850.0,United Kingdom
536366,22633,HAND WARMER UNION JACK,6,12/01/2010 08:28,1.85,17850.0,United Kingdom
536367,84969,RECIPE BOX WITH METAL HEART,32,12/01/2010 08:34,9.95,13047.0,United Kingdom
536368,22960,YELLOW COAT RACK PARIS FASHION,6,12/01/2010 08:34,4.95,13047.0,United Kingdom
536369,21756,BATH BUILDING BLOCK WORD,3,12/01/2010 08:35,5.95,13047.0,United Kingdom
...,...,...,...,...,...,...,...
C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,12/09/2011 09:27,2.08,16446.0,United Kingdom
C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,12/09/2011 09:57,1.95,14397.0,United Kingdom
C581499,M,Manual,-1,12/09/2011 10:28,224.69,15498.0,United Kingdom
C581568,21258,VICTORIAN SEWING BOX LARGE,-5,12/09/2011 11:57,10.95,15311.0,United Kingdom
C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,12/09/2011 11:58,1.25,17315.0,United Kingdom

In [7]:
data.groupby('StockCode').max()
# group the row by column StockCode, and select the max value from each different column to be shown in the table

<ipython-input-7-abe775a9b6e7>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  data.groupby('StockCode').max()

,InvoiceNo,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
StockCode,,,,,,
10002,551429,180,4/28/2011 15:05,1.66,18079.0,United Kingdom
10080,577801,170,9/27/2011 9:24,0.85,18096.0,United Kingdom
10120,580502,30,9/28/2011 15:18,0.21,18043.0,United Kingdom
10123C,560213,3,7/15/2011 15:05,0.65,17967.0,United Kingdom
10123G,549349,-38,04/08/2011 11:13,0.00,NaN,United Kingdom
...,...,...,...,...,...,...
gift_0001_20,573585,10,6/24/2011 15:51,17.02,NaN,United Kingdom
gift_0001_30,565231,30,8/30/2011 10:48,25.53,NaN,United Kingdom
gift_0001_40,561513,1,7/27/2011 15:12,34.04,NaN,United Kingdom
gift_0001_50,558614,1,6/30/2011 15:56,42.55,NaN,United Kingdom
m,539736,1,12/21/2010 15:18,2.55,NaN,United Kingdom

In [8]:
data.groupby('Country').count()
# group the row by column country, and want to show the count or number of value value from each column to be shown

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID
Country,,,,,,,
Australia,1259,1259,1259,1259,1259,1259,1259
Austria,401,401,401,401,401,401,401
Bahrain,19,19,19,19,19,19,17
Belgium,2069,2069,2069,2069,2069,2069,2069
Brazil,32,32,32,32,32,32,32
Canada,151,151,151,151,151,151,151
Channel Islands,758,758,758,758,758,758,758
Cyprus,622,622,622,622,622,622,622
Czech Republic,30,30,30,30,30,30,30
Denmark,389,389,389,389,389,389,389
EIRE,8196,8196,8196,8196,8196,8196,7485
European Community,61,61,61,61,61,61,61
Finland,695,695,695,695,695,695,695
France,8557,8557,8557,8557,8557,8557,8491
Germany,9495,9495,9495,9495,9495,9495,9495
Greece,146,146,146,146,146,146,146
Hong Kong,288,288,288,288,288,288,0
Iceland,182,182,182,182,182,182,182
Israel,297,297,297,297,297,297,250
Italy,803,803,803,803,803,803,803
Japan,358,358,358,358,358,358,358
Lebanon,45,45,45,45,45,45,45
Lithuania,35,35,35,35,35,35,35
Malta,127,127,127,127,127,127,127
Netherlands,2371,2371,2371,2371,2371,2371,2371
Norway,1086,1086,1086,1086,1086,1086,1086
Poland,341,341,341,341,341,341,341
Portugal,1519,1519,1519,1519,1519,1519,1480
RSA,58,58,58,58,58,58,58
Saudi Arabia,10,10,10,10,10,10,10
Singapore,229,229,229,229,229,229,229
Spain,2533,2533,2533,2533,2533,2533,2533
Sweden,462,462,462,462,462,462,462
Switzerland,2002,2002,2002,2002,2002,2002,1877
USA,291,291,291,291,291,291,291
United Arab Emirates,68,68,68,68,68,68,68
United Kingdom,495478,495478,494024,495478,495478,495478,361878
Unspecified,446,446,446,446,446,446,244

In [9]:
data.groupby('InvoiceNo')['StockCode'].apply(list)
# Group the row by column InvoiceNo, and combine the stock code & show it

InvoiceNo
536365     [85123A, 71053, 84406B, 84029G, 84029E, 22752,...
536366                                        [22633, 22632]
536367     [84879, 22745, 22748, 22749, 22310, 84969, 226...
536368                          [22960, 22913, 22912, 22914]
536369                                               [21756]
                                 ...
C581484                                              [23843]
C581490                                       [22178, 23144]
C581499                                                  [M]
C581568                                              [21258]
C581569                                       [84978, 20979]
Name: StockCode, Length: 25900, dtype: object

In [10]:
transactions = data.groupby('InvoiceNo')['StockCode'].apply(list)

## Association Rules

In [11]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5955 sha256=67a074d69867f9afc55fc2308731f2444043f417d85f56ec407c4ed92335ee33
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [12]:
from apyori import apriori

In [18]:
frequentItemsets = list(apriori(transactions,min_support = 0.065))
frequentItemsets

[RelationRecord(items=frozenset({'22423'}), support=0.08386100386100385, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22423'}), confidence=0.08386100386100385, lift=1.0)]),
 RelationRecord(items=frozenset({'47566'}), support=0.06586872586872587, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'47566'}), confidence=0.06586872586872587, lift=1.0)]),
 RelationRecord(items=frozenset({'85099B'}), support=0.08243243243243244, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B'}), confidence=0.08243243243243244, lift=1.0)]),
 RelationRecord(items=frozenset({'85123A'}), support=0.08671814671814672, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85123A'}), confidence=0.08671814671814672, lift=1.0)])]

In [19]:
len(frequentItemsets)

4

In [20]:
frequentItemsets[0][0]

frozenset({'22423'})

In [21]:
dir(frequentItemsets[0][0])

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'copy',
 'difference',
 'intersection',
 'isdisjoint',
 'issubset',
 'issuperset',
 'symmetric_difference',
 'union']

In [22]:
frequentItemsets[0][0].__len__()

1

In [25]:
min_sup = 0.03

frequentItemsets = list(apriori(transactions,min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({'85099B', '22386'}), support=0.03216216216216216, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B', '22386'}), confidence=0.03216216216216216, lift=1.0), OrderedStatistic(items_base=frozenset({'22386'}), items_add=frozenset({'85099B'}), confidence=0.6766856214459789, lift=8.20897311262335), OrderedStatistic(items_base=frozenset({'85099B'}), items_add=frozenset({'22386'}), confidence=0.39016393442622943, lift=8.20897311262335)])
yes
RelationRecord(items=frozenset({'22699', '22697'}), support=0.03027027027027027, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22699', '22697'}), confidence=0.03027027027027027, lift=1.0), OrderedStatistic(items_base=frozenset({'22697'}), items_add=frozenset({'22699'}), confidence=0.7417218543046358, lift=17.1523178807947), OrderedStatistic(items_base=frozenset({'22699'}), items_add=frozenset({'22697'}), confidence=0.7, lift=17.1523178807947)])

RelationRecord(items=frozenset({'85099B', '22386'}),

support=0.03216216216216216,

ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B', '22386'}), confidence=0.03216216216216216, lift=1.0),

OrderedStatistic(items_base=frozenset({'22386'}), items_add=frozenset({'85099B'}), confidence=0.6766856214459789, lift=8.20897311262335),

OrderedStatistic(items_base=frozenset({'85099B'}), items_add=frozenset({'22386'}), confidence=0.39016393442622943, lift=8.20897311262335)])

In [35]:
set(data[(data['StockCode']=='22699') | (data['StockCode']=='22697')]['Description'])

{'GREEN REGENCY TEACUP AND SAUCER', 'ROSES REGENCY TEACUP AND SAUCER '}

In [30]:
set(data[data['StockCode']=='22697']['Description'])

{'GREEN REGENCY TEACUP AND SAUCER'}

RelationRecord(items=frozenset({'22699', '22697'}),

support=0.03027027027027027,

ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22699', '22697'}), confidence=0.03027027027027027, lift=1.0),

OrderedStatistic(items_base=frozenset({'22697'}), items_add=frozenset({'22699'}), confidence=0.7417218543046358, lift=17.1523178807947),

OrderedStatistic(items_base=frozenset({'22699'}), items_add=frozenset({'22697'}), confidence=0.7, lift=17.1523178807947)])

In [36]:
set(data[(data['StockCode']=='22699') | (data['StockCode']=='22697')]['InvoiceNo'])

{'569415',
 'C558255',
 '570258',
 '558119',
 '574076',
 '566255',
 '548860',
 '568655',
 '579267',
 '559510',
 '554959',
 '544887',
 '538177',
 '573320',
 '545696',
 '563896',
 '552614',
 '542087',
 '557431',
 '553718',
 '565724',
 '556237',
 '561702',
 '540662',
 '565748',
 '550210',
 'C560588',
 '537666',
 '537042',
 '565862',
 '550638',
 '546498',
 '566976',
 '560976',
 '554054',
 '562608',
 '564835',
 '537313',
 '540981',
 '558073',
 '552149',
 '572028',
 '579512',
 '546007',
 '573125',
 '568676',
 '547841',
 '570374',
 '573892',
 '581345',
 '548194',
 '543107',
 '561894',
 '581498',
 '558030',
 '549730',
 '546892',
 '542344',
 '567673',
 '578354',
 '543530',
 '548714',
 '576388',
 '549587',
 '546683',
 '536980',
 '559886',
 '546643',
 'C566758',
 '549295',
 '544305',
 '553612',
 '555278',
 '554329',
 '549222',
 '546008',
 '575607',
 '558262',
 '538371',
 '550125',
 '555743',
 '557859',
 '565286',
 '577076',
 '562417',
 '557605',
 '553542',
 '556826',
 '541423',
 '550519',
 '540371',
 '555574',
 '564221',
 '537830',
 '568781',
 '575176',
 '556205',
 '569918',
 '580727',
 '549124',
 '576381',
 '563076',
 '563169',
 '571550',
 '544067',
 '550186',
 '537254',
 '557735',
 '542779',
 '561631',
 '566290',
 '567671',
 '564541',
 '538148',
 '568193',
 '560826',
 '548808',
 'C574548',
 '549435',
 'C560560',
 '545701',
 '567507',
 '562717',
 '553869',
 '570127',
 '544664',
 '537237',
 '572655',
 'C556644',
 '556503',
 '566396',
 '576690',
 'C537834',
 '575185',
 '568346',
 '540259',
 '554514',
 '545020',
 '571433',
 '579012',
 '547936',
 '567656',
 '552514',
 '576246',
 '571931',
 '569246',
 '550915',
 '563549',
 '552315',
 '565841',
 '566583',
 '545474',
 '572274',
 '553035',
 '550205',
 '539708',
 '563477',
 '541859',
 '577298',
 '572092',
 '562711',
 '570388',
 '553543',
 '560780',
 '554643',
 '559055',
 '554382',
 '559357',
 '559337',
 '551885',
 'C545033',
 '570688',
 '570187',
 '551005',
 '576618',
 '559878',
 '543251',
 '544208',
 '558565',
 '544833',
 '541695',
 '555488',
 '566326',
 '554974',
 '548648',
 '563584',
 '571746',
 '578149',
 '542543',
 '564755',
 '544657',
 '544314',
 '576329',
 '545812',
 '543826',
 'C551511',
 '536946',
 '570514',
 '576644',
 '558348',
 '560473',
 '543923',
 '571283',
 '552843',
 '566559',
 '567128',
 '557262',
 '578936',
 '552247',
 '559553',
 '558702',
 '547547',
 '568553',
 '575206',
 '578994',
 '562933',
 '549016',
 '559639',
 '550968',
 '562770',
 '537022',
 '537642',
 '543277',
 '556256',
 '564092',
 '581023',
 '544824',
 '560357',
 '544684',
 '559942',
 '543045',
 '572897',
 '563505',
 '544779',
 '571508',
 '557481',
 '554036',
 '567922',
 '566607',
 '577358',
 '544778',
 '560451',
 '538880',
 '578949',
 '547249',
 '548547',
 '567324',
 '566577',
 '580501',
 '555276',
 '573580',
 '572613',
 '543565',
 '578827',
 '555524',
 '553546',
 '549592',
 '562934',
 '539451',
 '541130',
 '565917',
 'C561232',
 '575138',
 '559493',
 '559124',
 '576339',
 '540464',
 '551531',
 '540839',
 '537823',
 '540465',
 '550438',
 '565781',
 '551564',
 '554139',
 '558683',
 '571216',
 '559494',
 '566446',
 '548210',
 '548663',
 '565994',
 '567793',
 '577258',
 '567670',
 '569555',
 '556284',
 '558526',
 '548983',
 '545445',
 '547498',
 '560236',
 '547949',
 '546367',
 '546314',
 '548192',
 '540992',
 '546980',
 '566193',
 '543451',
 '544081',
 '566581',
 'C559949',
 '577071',
 '562374',
 '541932',
 '544574',
 '574334',
 '577597',
 '545681',
 '537378',
 '555594',
 '544095',
 '569834',
 '550265',
 '567336',
 '579572',
 '564057',
 '566624',
 'C558434',
 '566060',
 '566482',
 '550503',
 '551717',
 '566985',
 '549296',
 '551414',
 '549425',
 '575946',
 '573083',
 '540364',
 '569137',
 '544456',
 '575930',
 '566988',
 'C550648',
 '565849',
 '544434',
 '546760',
 '536865',
 '570701',
 '565519',
 '536544',
 '566400',
 '537176',
 '553535',
 '548718',
 '550333',
 '576840',
 '547967',
 '556206',
 '567873',
 '564552',
 '560590',
 '546158',
 '560398',
 '568048',
 '536530',
 '549261',
 '539593',
 '545014',
 '561645',
 '552257',
 '540154',
 '541280',
 '552642',
 'C565848',
 '564301',
 '541576',
 '554560',
 '564857',
 '537638',
 '579711',
 '553191',
 '563922',
 'C540393',
 '561070',
 '555848',
 '566602',
 '542619',
 '544928',
 '543602',
 '565231',
 '554798',
 '561798',
 '561394',
 '544338',
 '546545',
 '571546',
 '580983',
 '537645',
 '548734',
 '569493',
 '544207',
 '580173',
 '548522',
 '555499',
 '577691',
 '564975',
 '558475',
 '565056',
 '545176',
 '540005',
 '579187',
 '550025',
 '537688',
 '564184',
 '551825',
 '552259',
 '556082',
 '537435',
 '569737',
 '544339',
 'C562953',
 '549997',
 '553684',
 '558443',
 '547360',
 '568651',
 '578314',
 '554557',
 '550921',
 '568955',
 '539736',
 '575931',
 '570834',
 '565424',
 '545058',
 '560225',
 '561637',
 '554714',
 '570677',
 '580730',
 '558904',
 '566572',
 '570086',
 '543019',
 '552857',
 '579102',
 '566788',
 '581122',
 '558089',
 '559134',
 '554842',
 '566720',
 '544888',
 '553162',
 '574950',
 '545377',
 '562553',
 '578031',
 '579885',
 '542719',
 '544596',
 '560906',
 '554813',
 '577518',
 'C543633',
 '555925',
 '546442',
 '551599',
 '549305',
 '546992',
 'C545724',
 '564817',
 '566790',
 '572854',
 '568411',
 '560504',
 '546669',
 '551174',
 'C555598',
 '581217',
 '537335',
 '541008',
 '541949',
 '575477',
 '550987',
 '564091',
 'C567955',
 '545343',
 'C544665',
 '546896',
 'C550664',
 '557616',
 '564838',
 '579297',
 '556073',
 '572969',
 '542115',
 '543106',
 '553541',
 '574368',
 '577078',
 '569419',
 '555109',
 '545428',
 '552231',
 'C555254',
 '567293',
 '559923',
 '552665',
 '546562',
 '569917',
 '575484',
 '565150',
 '543989',
 '574893',
 '536624',
 '569568',
 '541219',
 '572758',
 '580729',
 '537434',
 '550914',
 '565916',
 '575063',
 '551960',
 '566537',
 '537470',
 '544075',
 '560580',
 '579196',
 '545426',
 '563353',
 '556323',
 '578817',
 '546315',
 '551343',
 'C558312',
 '556095',
 '563561',
 '568310',
 '564758',
 '554030',
 '538883',
 '548987',
 '552563',
 '545464',
 '555695',
 '553709',
 '543201',
 '550899',
 '573338',
 '547107',
 '571714',
 '562166',
 '545912',
 '571377',
 '554483',
 '574298',
 '554310',
 'C578144',
 '566871',
 '559693',
 'C564212',
 'C567358',
 '574731',
 '558315',
 '543909',
 '544812',
 '546888',
 '547846',
 '572549',
 '555150',
 '568804',
 '547788',
 '539738',
 '539739',
 '553462',
 '538660',
 '568574',
 '552687',
 '542691',
 '548333',
 '553566',
 '548260',
 '548373',
 '548514',
 '562429',
 '541810',
 '548003',
 '551339',
 '575875',
 '561355',
 '571058',
 '545568',
 '561051',
 '539752',
 '557064',
 '574852',
 '557560',
 '581170',
 '545467',
 '579927',
 '540646',
 '581495',
 '566094',
 '546660',
 '556783',
 '572552',
 '572066',
 '565331',
 '536627',
 '548212',
 '544768',
 '571745',
 '536862',
 '563614',
 '554026',
 '568060',
 '560777',
 '554124',
 '541960',
 '555854',
 '561371',
 '537887',
 '560634',
 '549750',
 'C564854',
 '545063',
 '562849',
 '553461',
 '577498',
 '558240',
 '562607',
 '547385',
 '555486',
 '550474',
 '563442',
 'C538059',
 '542255',
 'C566084',
 '551352',
 '548896',
 '575324',
 '572751',
 '559827',
 '545945',
 '561455',
 '546915',
 '575739',
 '569545',
 '580610',
 '548516',
 '543629',
 '555722',
 '544055',
 '549525',
 '551995',
 '580367',
 '544681',
 '558103',
 '538566',
 '572212',
 'C555358',
 '565214',
 '554326',
 '573553',
 'C545828',
 '553891',
 '555158',
 '539442',
 '560790',
 '577512',
 '547828',
 '577029',
 '557034',
 '562534',
 '545340',
 '564065',
 '547378',
 '562282',
 '568199',
 '550989',
 '570257',
 '556501',
 '556821',
 '541421',
 '550471',
 '545022',
 '537754',
 '559817',
 '570597',
 '544201',
 '549746',
 '581439',
 '539564',
 '550314',
 '543097',
 '556016',
 '550215',
 '556636',
 '552232',
 '577610',
 '539737',
 '568369',
 '550500',
 '539437',
 'C559667',
 '579694',
 '581238',
 '572229',
 '554921',
 '578344',
 'C556268',
 '560604',
 '551953',
 '573576',
 '565919',
 '546927',
 '561698',
 '553002',
 '547096',
 '566477',
 '553901',
 '541506',
 '556577',
 '537179',
 '552678',
 '554958',
 '570713',
 '545667',
 '557500',
 '571441',
 '565151',
 '575620',
 '547063',
 '539436',
 '552270',
 '551860',
 '550958',
 '544677',
 '552336',
 '550213',
 '566170',
 '570227',
 '554110',
 '549852',
 'C538124',
 '579508',
 '538524',
 '552540',
 '555327',
 '547580',
 '564974',
 '548409',
 '549909',
 '576899',
 'C545449',
 '565234',
 '551160',
 '557117',
 '554158',
 '573822',
 '564172',
 '542600',
 '553182',
 '577355',
 '564825',
 '576616',
 'C550808',
 '565289',
 '574707',
 '563193',
 '572553',
 '553870',
 '559173',
 '578044',
 'C579945',
 '561217',
 '543732',
 '557672',
 '577020',
 '543055',
 '541133',
 '571034',
 '547399',
 '560895',
 'C542263',
 '541129',
 '549999',
 '557301',
 '550468',
 '566257',
 '550251',
 '552449',
 '569544',
 '577319',
 '575221',
 '542349',
 '553946',
 '557259',
 '544421',
 '555870',
 '577400',
 '568988',
 '558777',
 '554113',
 '564432',
 '574328',
 'C546125',
 '548894',
 '568057',
 '545690',
 '541584',
 'C577752',
 '547493',
 '561820',
 '536592',
 '580665',
 '566597',
 '541110',
 '538370',
 '542583',
 '560773',
 '567905',
 '547400',
 '561125',
 '562222',
 '571446',
 '545721',
 '552323',
 '558918',
 '558120',
 '558681',
 '581006',
 '563909',
 '566600',
 '561633',
 '564306',
 '565675',
 '562273',
 '543533',
 '559800',
 '558770',
 '562377',
 '540915',
 '571219',
 '552715',
 '563931',
 '537396',
 '545475',
 '538071',
 '552196',
 '559938',
 '565847',
 '573778',
 '567639',
 '579518',
 '565396',
 '545320',
 '546891',
 'C567885',
 'C553479',
 '559679',
 '555147',
 '562955',
 '577531',
 '536804',
 '545154',
 '580612',
 '540026',
 '578347',
 '560291',
 '570824',
 'C549840',
 '543532',
 '548974',
 '562365',
 '551997',
 '579751',
 '545214',
 '575866',
 'C572410',
 '543486',
 '545719',
 '548159',
 '580053',
 '552308',
 '544749',
 '558372',
 '540777',
 'C562921',
 '553671',
 '566981',
 '545429',
 '564300',
 '550183',
 'C574507',
 '556927',
 '570428',
 '553013',
 '577500',
 'C555253',
 '554704',
 '543036',
 '542389',
 '555522',
 '538903',
 '558885',
 '570720',
 '571061',
 '559112',
 'C539467',
 '581059',
 '575846',
 'C545525',
 '556259',
 '574739',
 '537738',
 '550307',
 '540372',
 '542647',
 '541495',
 '545411',
 '559941',
 '556415',
 '554028',
 '581472',
 '561651',
 'C562375',
 '548739',
 '568134',
 '539450',
 '562573',
 '545526',
 '569367',
 '545216',
 '539742',
 '553768',
 '562202',
 '551062',
 '572550',
 '546306',
 '579539',
 '546849',
 '578844',
 '551014',
 '571560',
 '540418',
 '555106',
 '554935',
 '549056',
 '575947',
 '553385',
 '573397',
 '544205',
 '563384',
 '540499',
 '542999',
 '563910',
 '553607',
 '576837',
 '543099',
 '544913',
 '569570',
 'C562119',
 '565838',
 '542881',
 '545895',
 '580673',
 'C542413',
 '576672',
 '551334',
 '563534',
 '575490',
 '580669',
 '565223',
 '566731',
 '579093',
 '555275',
 '552694',
 '539217',
 '550437',
 '537240',
 '567157',
 '553202',
 '577039',
 '573070',
 '548559',
 '548893',
 '550470',
 '558864',
 '536876',
 '559525',
 '563906',
 '555400',
 '543973',
 '545759',
 '543487',
 '542622',
 '579471',
 '561236',
 '567341',
 '571241',
 'C564964',
 '579445',
 '571797',
 'C545444',
 ...}

In [37]:
data[data['InvoiceNo']=='562950']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
297488,562950,22752,SET 7 BABUSHKA NESTING BOXES,2,08/11/2011 09:56,8.50,15608.0,United Kingdom
297489,562950,22755,SMALL PURPLE BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297490,562950,22753,SMALL YELLOW BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297491,562950,22754,SMALL RED BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297492,562950,22757,LARGE RED BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297493,562950,22758,LARGE PURPLE BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297494,562950,22756,LARGE YELLOW BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297495,562950,23310,BUBBLEGUM RING ASSORTED,36,08/11/2011 09:56,0.42,15608.0,United Kingdom
297496,562950,23280,FOLDING BUTTERFLY MIRROR HOT PINK,12,08/11/2011 09:56,0.83,15608.0,United Kingdom
297497,562950,22383,LUNCH BAG SUKI DESIGN,10,08/11/2011 09:56,1.65,15608.0,United Kingdom
297498,562950,22492,MINI PAINT SET VINTAGE,36,08/11/2011 09:56,0.65,15608.0,United Kingdom
297499,562950,71459,HANGING JAM JAR T-LIGHT HOLDER,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297500,562950,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297501,562950,21175,GIN + TONIC DIET METAL SIGN,12,08/11/2011 09:56,2.55,15608.0,United Kingdom
297502,562950,23164,REGENCY CAKE SLICE,4,08/11/2011 09:56,4.95,15608.0,United Kingdom
297503,562950,23245,SET OF 3 REGENCY CAKE TINS,4,08/11/2011 09:56,4.95,15608.0,United Kingdom
297504,562950,23171,REGENCY TEA PLATE GREEN,12,08/11/2011 09:56,1.65,15608.0,United Kingdom
297505,562950,22697,GREEN REGENCY TEACUP AND SAUCER,6,08/11/2011 09:56,2.95,15608.0,United Kingdom